### PR TITLE
Issue #686 Fixed

### PR DESCRIPTION
**Pull request by Shikib**
Fixed all of the false positive issues with warning 1012 (invalid code injection). Doesn't falsely generate a warning message for situations where a class is attempting to inject into an extended method.

### CODE REVIEW

**Comment by vahdat-ab** [comment]
@Shikib 
I wonder if you get the following warnings as well?
     [java] Warning 1012 on line 490 of file "Umple.ump":
     [java] Method 'setPackageName' cannot be found. Injection was ignored.
     [java] Warning 1012 on line 491 of file "Umple.ump":
     [java] Method 'addDepend' cannot be found. Injection was ignored.
     [java] Warning 1012 on line 563 of file "Umple.ump":
     [java] Method 'addDepend' cannot be found. Injection was ignored.
     [java] Warning 1012 on line 565 of file "Umple.ump":
     [java] Method 'setImmutable' cannot be found. Injection was ignored.
     [java] Warning 1012 on line 571 of file "Umple.ump":
     [java] Method 'addStateMachine' cannot be found. Injection was ignored.
     [java] Warning 1012 on line 643 of file "Umple.ump":
     [java] Method 'setImmutable' cannot be found. Injection was ignored.
     [java] Warning 1012 on line 647 of file "Umple.ump":
     [java] Method 'setExtendsTrait' cannot be found. Injection was ignored.
     [java] Warning 1012 on line 649 of file "Umple.ump":
     [java] Method 'addStateMachine' cannot be found. Injection was ignored.
     [java] Warning 1012 on line 762 of file "Umple.ump":
     [java] Method 'setType' cannot be found. Injection was ignored.
     [java] Warning 1012 on line 763 of file "Umple.ump":
     [java] Method 'setType' cannot be found. Injection was ignored.
     [java] Warning 1012 on line 891 of file "Umple.ump":
     [java] Method 'setUmpleClass' cannot be found. Injection was ignored.
     [java] Warning 1012 on line 60 of file "Structure.ump":
     [java] Method 'setUmpleClass' cannot be found. Injection was ignored.

**Comment by Shikib** [comment]
The previously compiled jar isn't what's used during the umpleSelf section of the build. To see what the build would look like after the merge, what you should do is `java -jar dist/umple.jar cruise.umple/src/Master.ump`. During a full build, I believe the previously downloaded version of umple is used.

**Comment by TimLethbridge** [comment]
Yes exactly; you won't see the effect of this PR until it is merged unless you prevent the built jar from being downloaded during the build.

**Comment by vahdat-ab** [comment]
so I'm merging

**Pull request merged**
