### PR TITLE
Tentative pull request for issue988 rule b)

### PR DESCRIPTION
**Pull request by BernardYuan**
Tentative for issue#988 rule b), just see whether it would pass CI because it passed my local double-full build.

### CODE REVIEW

**Comment by TimLethbridge** [comment]
Ok this seems to work. But all it does is undo the commenting out. Not sure *why* it works.

Note that you had said
```
class GenConstructor{
	0..1 -- * GenMethodParameter parameters;
	0..1 -- * GenParentMethodParameter parentParameters;
}
class GenMethodParameter {}
class GenParentMethodParameter {
  isA GenMethodParameter;
}
```

Is code found in the compiler that should trigger error 19 because the 0..1 side needs a different role name in one of the associations (otherwise both associations use the same variable on the GenConstructor side which is bug-prone). So why has the problem gone away with this new PR?

**Comment by BernardYuan** [comment]
I have just compiled the given example with this version of Umple, which, in fact, failed. 

It is for sure that this branch should not be merged, however, I think one thing that would require debugging is the effectiveness of the CI procedure. Probably there are some problems with it that it overlooks some certain errors.

**Comment by TimLethbridge** [comment]
I am going to see about fixing the CI tomorrow if I can, so that a regular full build and also a Travis build would fail if they damage the compiler. But it might take longer than tomorrow.

**Comment by BernardYuan** [comment]
After refactoring it seems now the compiler can pass the CI.

**Pull request merged**
