### PR TITLE
Fixes 984 and 992

### PR DESCRIPTION
**Pull request by AdamBJ**
See https://github.com/umple/umple/pull/993#issue-205489853 for what this PR does. I'm making a new PR rather than using 993 because I rebased in a dumb way and messed up the commit history of the `984` branch.

### CODE REVIEW

**Comment by AdamBJ** [comment]
The build didn’t pass CI on Mac. I’m looking into why, sorry! I did a full build on my machine, I must have missed a failure somewhere

**Comment by AdamBJ** [comment]
@vahdat-ab I did another full build locally, there aren't any errors. Here's the build output: 
https://gist.github.com/AdamBJ/faac94caa040a1e412dbe43f93d8466d

I'm not sure what's wrong. I didn't have any problems locally, and the build completed on Linux successfully. Is there any way to run the CI again? Maybe it's just "one of those things"?

**Comment by AdamBJ** [comment]
I can't rerun the travis build for this since the PR has been merged... I'll try to figure out another way

**Comment by AdamBJ** [comment]
It looks like the travis checks on master with my changes included are fine: https://travis-ci.org/umple/umple/builds/205684014

**Comment by vahdat-ab** [comment]
@AdamBJ everything looks ok :-)

**Pull request merged**
