### PR TITLE
Fixed the bug which triggers wrong templates.

### PR DESCRIPTION
**Pull request by BernardYuan**
Fixed the bug which triggers wrong templates. By labelling each association variable with correct *relevantEnd* value.

### CODE REVIEW

**Comment by TimLethbridge** [comment]
@BernardYuan - Travis is failing with the following error"

/Users/travis/build/umple/umple/build/build.exampletests.xml:206: Failed to compile Java code generated from assocSpecEx.ump

This means that the example in the file with that name umpleunline/ump/manualexampes/assocSpecEx.ump
is not resulting in compilable code. You can figure out why by simply compiling it and seeing the java error. You should have seen this if you did a full build.

**Comment by BernardYuan** [comment]
My local full build, which was run twice, passed all the tests. Is there any other way to debug this on the CI?

**Comment by TimLethbridge** [comment]
I suspect your full build is failing, but you haven't noticed. If you run the 'devtools/bumple' script it will search for words indicating failure.

But you can see the results on the CI that have failed anyway. Seeing the problem is easy! You know which file is failing: umpleunline/ump/manualexampes/assocSpecEx.ump

Just compile it on the command line with the -c- option and it should show that it is generating bad java. Inspect the Java to see what needs fixing.

**Comment by TimLethbridge** [comment]
The failures occurring in assocSpecEx.ump are the following (the items point to .ump files, but it is the generated java that has a problem).

```
assocSpecEx.ump:88: error: cannot find symbol
    return super.getVehicle();
                ^
  symbol: method getVehicle()
assocSpecEx.ump:93: error: cannot find symbol
    return super.getVehicle();
                ^
  symbol: method getVehicle()
assocSpecEx.ump:121: error: cannot find symbol
    wasSet = super.setVehicle(aVehicle);
                  ^
  symbol: method setVehicle(Bicycle)
assocSpecEx.ump:135: error: incompatible types: Vehicle cannot be converted to Bicycle
      Bicycle placeholderVehicle = getVehicle();
                                             ^
assocSpecEx.ump:59: error: wheel has private access in Vehicle
    Wheel aWheel = (Wheel)wheel.get(index);
                          ^
assocSpecEx.ump:67: error: wheel has private access in Vehicle
    List<? extends Wheel> newWheel = Collections.unmodifiableList(wheel);
                                                                  ^
assocSpecEx.ump:84: error: wheel has private access in Vehicle
    if (wheel.contains(aWheel)) { return false; }
        ^
assocSpecEx.ump:90: error: incompatible types: Vehicle cannot be converted to Bicycle
    Bicycle existingVehicle = aWheel.getVehicle();
                                               ^
assocSpecEx.ump:102: error: wheel has private access in Vehicle
      wheel.add(aWheel);
      ^
assocSpecEx.ump:111: error: wheel has private access in Vehicle
    if (wheel.contains(aWheel))
        ^
assocSpecEx.ump:113: error: wheel has private access in Vehicle
      wheel.remove(aWheel);
      ^
assocSpecEx.ump:127: error: wheel has private access in Vehicle
      wheel.remove(aWheel);
      ^
assocSpecEx.ump:128: error: wheel has private access in Vehicle
      wheel.add(index, aWheel);
      ^
assocSpecEx.ump:137: error: wheel has private access in Vehicle
    if(wheel.contains(aWheel))
       ^
assocSpecEx.ump:141: error: wheel has private access in Vehicle
      wheel.remove(aWheel);
      ^
assocSpecEx.ump:142: error: wheel has private access in Vehicle
      wheel.add(index, aWheel);
      ^
assocSpecEx.ump:63: error: wheel has private access in Vehicle
    return (Wheel)wheel.get(0);
                  ^
assocSpecEx.ump:88: error: wheel has private access in Vehicle
    wheel = new ArrayList<Wheel>();wheel.add(aNewWheel);
    ^
assocSpecEx.ump:88: error: wheel has private access in Vehicle
    wheel = new ArrayList<Wheel>();wheel.add(aNewWheel);
                                   ^
assocSpecEx.ump:93: error: wheel has private access in Vehicle
      for (Wheel orphan : wheel)
                          ^
20 errors
Processed assocSpecEx.ump.
```

**Comment by BernardYuan** [comment]
All test passed. The previous error was caused by a logical error in dealing with specialization template.

**Pull request merged**
