### PR TITLE
Added logic to avoid comparisons with boolean true/false values

### PR DESCRIPTION
**Pull request by tlaport4**
**IMPORTANT**: By submitting a patch, you agree that your work will be licensed under the [license](https://github.com/umple/umple/blob/master/LICENSE.md) used by the project.

If your pull request does not pass CI, it will **not** be merged (unless _heavily_ justified). 
## Description

Please provide a description of what this PR is meant to fix, and how it works (if it's not clear from the code changes). 
## Tests

Please list all major test changes. All issues should have a test created to address the issue in the future (as relevant). 

If closing issues, please write `Closes #ISSUE_NUMBER[, #ISSUE_NUMBER2, ...]`, to automatically close the equivalent issue.

**Note:** This template is a guide, remove sections as applicable.

### CODE REVIEW

**Comment by tlaport4** [comment]
Forgot to push new .ump test file. Fixing now

**Comment by TimLethbridge** [comment]
I am going to merge this PR. Please next time make sure that you. Add the issue number to the description and also  give a proper description (delete the template and replace it by what the PR actually does).

**Comment by tlaport4** [comment]
Oh right sorry. I'll definitely do that next time, my bad! And I'll update this one when I get a chance.

**Comment by vahdat-ab** [comment]
@tlaport4  would mind let me know this is related to which issue? we need to close it

**Pull request merged**
