### PR TITLE
Added missing bracket for Java JET template

### PR DESCRIPTION
**Pull request by Diusrex**
The original code was missing the third case, and so would not always
add a ().

Fixes issue #696

### CODE REVIEW

**Comment by Diusrex** [comment]
In the travis-ci log:

```
==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u72-b15/jdk-8u72-ma
######################################                                    54.0%
curl: (18) transfer closed with 109725217 bytes remaining to read
Error: Download failed on Cask 'java' with message: Download failed: http://download.oracle.com/otn-pub/java/jdk/8u72-b15/jdk-8u72-macosx-x64.dmg
```

Then the [first main error](https://travis-ci.org/umple/umple/jobs/105484438#L2846) is "/Users/travis/build/umple/umple/build/build.deps.xml:194: java.lang.UnsupportedClassVersionError: cruise/umple/util/UmplecAntTask : Unsupported major.minor version 52.0", which seems like may have been using the wrong version of Java.
Looks like

**Comment by Diusrex** [comment]
Attempting to get Travis-CI to rebuild.

**Comment by vahdat-ab** [comment]
I did a full build and no failure in my machine.

**Comment by Diusrex** [comment]
Yea, after re-running Travis-CI it works

**Comment by vahdat-ab** [comment]
Thanks

**Pull request merged**
