### PR TITLE
Fixes issue for queued methods Java code generation and adds testbed test

### PR DESCRIPTION
**Pull request by ZainabAlShowely**
Corrects queued method generating non compiling code in Java.
Adds a basic testbed test checking proper execution of queued methods.

### CODE REVIEW

**Comment by TimLethbridge** [comment]
@ZainabAlShowely .. the appveyor test is failing with the following. Not sure if it is a bootstrapping problem (e.g. using the wrong version of the compiler to compiler new code ...).
```
Success! Processed C:\projects\umple\testbed\src\runtime\StateMachineEntry.ump.
1755    [javac] Compiling 139 source files to C:\projects\umple\testbed\bin
1756    [javac] C:\projects\umple\testbed\test\cruise\associations\AddAtIndexTest.java:5: error: cannot find symbol
1757    [javac] import cruise.associations.MentorAM;
1758    [javac]                           ^
1759    [javac]   symbol:   class MentorAM
1760    [javac]   location: package cruise.associations
1761    [javac] C:\projects\umple\testbed\test\cruise\associations\AddAtIndexTest.java:6: error: cannot find symbol
1762    [javac] import cruise.associations.StudentAM;
1763    [javac]                           ^
1764    [javac]   symbol:   class StudentAM
1765    [javac]   location: package cruise.associations
1766    [javac] C:\projects\umple\testbed\test\cruise\associations\AssociationClassTest.java:5: error: cannot find symbol
1767    [javac] import cruise.associations.Flight;
1768
```

**Comment by TimLethbridge** [comment]
@ZainabAlShowely It fails on my mac too after I do a first-build.

**Comment by ZainabAlShowely** [comment]
I see, I will run tests again to verify what exactly is wrong..

**Comment by TimLethbridge** [comment]
@ZainabAlShowely Actually before the Java errors, I am getting 
```
Error 130 on line 5 of file "TestHarnessQueuedMethod.ump":
     [java] Attribute name 'String[]Â log' must be alphanumeric, starting with a lower-case letter
```

This seems to be because of an extraneous character! Would you like me to try to fix?

**Comment by TimLethbridge** [comment]
I have fixed one error with the strange character.

**Comment by ZainabAlShowely** [comment]
I see, thank you! The character does not seem to be interpreted on my machine as tests seem to run correctly even after a first build.

**Comment by TimLethbridge** [comment]
@ZainabAlShowely Good news! On my machine the commit I did fixed the problem. The tests now pass. So I imagine they will pass here too. No need to look at this further.

**Pull request merged**
