### PR TITLE
Umple-TL, TestHarness, and Umple-TL tests from umple-tl

### PR DESCRIPTION
**Pull request by ahmedvc**

### CODE REVIEW

**Comment by Nava2** [comment]
Awesome job fixing up these commits to remove the conflicts.

Before this is merged, please do one more rebase and push. 

``` bash
git checkout f-umple-tl
git rebase -i master
```

Read the instructions in the editor that opens and you can merge the 5 commits into 2. You'll want to pick the first two, 'p', and squash the last three, 's'. 

If you look at your log, you'll see that the commits have been "squashed" into two commits.  

Then do `git push origin f-umple-tl` where `origin` is your remote. 

Great job, sorry it's so much effort. :+1:

**Comment by ahmedvc** [comment]
JDK; oraclejdk8 failed on Travis, while the other one passed. 
The build logs show java compilation errors.

**Comment by Nava2** [comment]
The linux build error is related to the original issue in #715. 

Edit: When you do the rebase, the pull request will automatically update. :)

**Comment by ahmedvc** [comment]
I picked the first two and squashed the rest, but after that publish and sync of the branch fail.

**Comment by ahmedvc** [comment]
[f-umple-tl]> git rebase -i master
Successfully rebased and updated refs/heads/f-umple-tl.
[f-umple-tl]> git push origin f-umple-tl
To https://github.com/ahmedvc/umple.git
 ! [rejected]        f-umple-tl -> f-umple-tl (non-fast-forward)
error: failed to push some refs to 'https://github.com/ahmedvc/umple.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by TimLethbridge** [comment]
OK I am going to test this manually. I think the Travis Linux problems are nothing to do with us. If all is OK I will merge and we will hopefully see it pass on Travis OSX and CC.

**Comment by Nava2** [comment]
@ahmedvc is the `git log` correct? If so, do `git push origin master -f`, you have to "force" the push because it's rewriting history.

**Comment by TimLethbridge** [comment]
It built fine on my machine. I believe it will be fine on Linux at cc.umple.org and on OSX at Travis. We will see

**Pull request merged**
