### PR TITLE
Resolve issue 140

### PR DESCRIPTION
**Pull request by jblang94**
This PR addresses #140 . It includes the following:
- If a user-defined state has the same name as Umple's "Final" keyword, the "E074 User Defined State Cannot be Named Final" error is thrown
- Umple's "Final" keyword defines the Final state for the top-level state machine. Upon transitioning to this state, "delete()" will be called
- For regional final states (i.e. final s1 {}), if they are in concurrent regions, a check is performed to see if all other state machines within the concurrent region are in their final states before calling "delete()"

### New Test Cases
UmpleParserStateMachineTest (to test E074)
- 488_stateNameIsFinal*.ump

StateMachineTest
- testFinalKeyword*.ump
- testRegionFinalStates_*.ump

### Updated Test Cases
UmpleParserStateMachineTest
- concurrentFinals
- finalStateInOneConcurrentRegion
- finalStateInTwoConcurrentRegions
- finalStateNoAction
- finalStateWithAction

FinalStatesTest
- CallDeleteAsSoonAsOneFinalStateIsReached, renamed to "CallDeleteWhenTransitionUsesFinalKeyword"

### CODE REVIEW

**Comment by jblang94** [comment]
@vahdat-ab thanks for your feedback, I am wondering if you could please clarify which of these events from your example isn't implementing the exits correctly? To me, it seems to be correct currently.

```
public boolean e()
{
  boolean wasEventProcessed = false;
  
  StatusS1S11S111 aStatusS1S11S111 = statusS1S11S111;
  switch (aStatusS1S11S111)
  {
    case s111:
      exitStatus(); // modular implementation calls the exit methods within s1 before going to
                    // Status.Final
      setStatus(Status.Final);
      wasEventProcessed = true;
      break;
    default:
      // Other states do respond to this event
  }

  return wasEventProcessed;
}


public boolean e2()
{
  boolean wasEventProcessed = false;
  
  Status aStatus = status;
  switch (aStatus)
  {
    case s1:
      exitStatus(); // modular implementation calls the exit methods within s1 before going to
                    // Status.s2
      setStatus(Status.s2);
      wasEventProcessed = true;
      break;
    default:
      // Other states do respond to this event
  }

  return wasEventProcessed;
}

public boolean e3()
{
  boolean wasEventProcessed = false;
  
  Status aStatus = status;
  switch (aStatus)
  {
    case s2:
      // There is no exit action for s2, and it has no nested state machines
      // s2's containing region is "status"
      setStatus(Status.s3);
      wasEventProcessed = true;
      break;
    default:
      // Other states do respond to this event
  }

  return wasEventProcessed;
}

public boolean e4()
{
  boolean wasEventProcessed = false;
  
  Status aStatus = status;
  switch (aStatus)
  {
    case s2:
      // There is no exit action for s2, and it has no nested state machines
      // s2's containing region is "status"
      setStatus(Status.Final);
      wasEventProcessed = true;
      break;
    default:
      // Other states do respond to this event
  }

  return wasEventProcessed;
}
```

**Comment by vahdat-ab** [comment]
->for reference:
Please consider the following example:
```
class X{
  status{
    s1{
      exit /{System.out.println("t4");}
      e2-> s2;
      s11{
        exit /{System.out.println("t3");}
        s111{
          exit /{System.out.println("t2");}
          s111{
            exit /{System.out.println("t1");}
            e-> Final;
          }
        }
      }
      
    } 
    s2{
      e4-> Final;
    e3-> s3;  
    } 
    final s3{}
  }
  
}
```
Your solution doesn't take care of exits.

**Comment by vahdat-ab** [comment]
It is ok, I think I have explored a wrong branch. Doing my final build, if it passes It'' merge this.

**Comment by vahdat-ab** [comment]
Check this example:
```
class X{
  status{
    s1{
      exit /{System.out.println("t4");}
      e2-> s2;
      s11{
        exit /{System.out.println("t3");}
        s111{
          exit /{System.out.println("t2");}
          s111{
            exit /{System.out.println("t1");}
            e-> Final;
            d1-> fState1;
          }
        }
      }
      final fState1{}
      ||
      s12{
        s122{
          d2->fState2;
        }
        final fState2{};
      }      
    } 
    s2{
      e4-> Final;
    e3-> s3;  
    } 
    final s3{}
  }
}
```
Event `d1` should not execute `System.out.println("t4")` because it is still inside the state `s1`. You have fixed this issue in the previous issue related to exits, but now it is back again. The code generated for `d2` is correct.

**Comment by jblang94** [comment]
@vahdat-ab thanks! just pushed my changes up

**Comment by vahdat-ab** [comment]
Thanks.

**Pull request merged**
