### PR TITLE
 Umple-TL, TestHarness, and Umple-TL tests

### PR DESCRIPTION
**Pull request by ahmedvc**
Umple-TL, TestHarness, and Umple-TL tests {

Nested template definition support
Dynamic test harness delivery
Umple-TL tests and resources
}

### CODE REVIEW

**Comment by ahmedvc** [comment]
Eclipse accidentally committed into umple master. The build log shows the following test case failure:
[cruise/umple/tracer/implementation/java/lttng/JavaLttngTracerTest.java added as cruise/umple/tracer/implementation/java/lttng/JavaLttngTracerTest.class doesn't exist.]]></message>
                <message priority="debug"><![CDATA

However, this testcase doesn't fail on my machine. I noticed even after I reverted the last changes, Travis still shows build failure for JDK: oraclejdk8.

**Comment by TimLethbridge** [comment]
I am looking into it

**Comment by TimLethbridge** [comment]
I am going to flag this for help to Kevin and Andrew as there are two situations:

Kevin and Andrew,

We have an awkeard Git/Travis situation.

Problem 1:

ahmedvc accidentally pushed Ia040550df9cdbf3a336de60c7996cebcca25df7f directly overnight when he meant to make a pull request

The build apparently failed (they don't tell me what the problem was, but it may have been a Travis CI problem unrelated to their commit, see below)

The original change Ia040550df9cdbf3a336de60c7996cebcca25df7f
Has
:  61 changed files  with 4,714 additions and 59 deletions.

Then they reverted it.

The TRAVIS CI build, however, keeps on failing on Linux. I note that 
it says on page https://travis-ci.org/umple/umple/jobs/107555225
which it never used to. Keving, can you tell us what is going on?

Problem 2:

ahmedvc then created

PR 715 on ahmedvc:master 

However this reports has conflicts that must be resolved

The PR
PR has   60 changed files  with 4,647 additions and 204 deletions.

The conflict I believe is only  related to en.error
But it is extremely bizarre since the PR is asking to update a very ancient version of en.error to add many new error messages that have been present for a long time, and to change the URL to http://cruise.eecs.uottawa.ca
The only messages to add to en.error are 3503 to 3508

I lack github skills. How can I resolve this PR to resolve the branch conflict (and in your help to me, please explain in detail why the instructions work, as I never seem to 'get it').

**Comment by TimLethbridge** [comment]
It seems that Java error 137 is returned on the Travis build, which means that Java was killed (signal 9 received). Perhaps Travis is interpreting the situation as 'Umple is consuming too many resources'

**Comment by Nava2** [comment]
I have a longer post coming, but please see travis-ci/travis-ci#5582 for more information about the failing build.

**Comment by Nava2** [comment]
Good morning!

I figure the best thing for me to do would be to outline my thought process as I go (might be jumbled, but it should hopefully give some context).
1. I pulled and built the HEAD of the repository -- `git pull upstream master` (I have upstream as umple/Umple because I work on my own fork as origin)
2. While it is building..
   1. The travis log says Java returned 137 -- I'm unsure what this error is
   2. Googling `java error code 137` tells me your intuition is right, Tim. It ran out of memory (link)
   3. This strongly suggests that someone has created a memory leak in the program
3. It built fine on my Mac -- I have a lot of memory, though
4. Since this seems to only affect smaller machines, looking back and "bisecting" the commits until it works..
5. Build 251 works, so lets check the commit differences.. The difference is massive -- this won't help
6. Looking towards the PR, we can see that there is a conflict (as Tim pointed out)
7. This conflict is because the changes being asked for directly conflict with the "revert" commit.
8. To fix this, @ahmedvc needs to rebase his branch with master manually (`git checkout my-branch; git merge rebase master`)
   - Rebasing is similar to merging except you're rewriting history - This means your branch's history will change and will add the two master commits into your history
   - **NEVER DO THIS WITH upstream/master AS THE "REBASEE"**
   - When you need to push your branch back, do `git push origin my-branch -f` The `-f` is for force because you're rewriting history. Never force push to a "public" branch like `master`

### PR Conflict

@TimLethbridge, the conflict needs to be resolved by @ahmedvc, not you!

### Build error

I actually don't see the problem. I restarted build 251.1 to see if it was a "fluke" that it was passing before. Something bad has happened.. I'm unsure why, but the Linux machines are not building anymore.

I've found a travis-ci issue that might address our problem, travis-ci/travis-ci#5582. It seems to be the same.

### Avoiding accidental commits to master (oops!) through bureaucracy

Github has tooling in place to allow/disallow people to commit to branches. I think this should be done for everyone except Tim and those who are UCOSP coordinators (i.e. Andrew/Vahdat). If we want to do this, I can do it quickly now. There is a blog post outlining what they are.

I propose that we do two things, though:

A) Protect the master branch -- stop ANYONE from force pushing and force everyone to use pull requests to push to master

B) Remove anyone except for "admins" from pushing to master (master is sacred!)

I did go ahead and create an umple team: "[Umple Team Leads](https://github.com/orgs/umple/teams)" that has administrative access to the Umple repository. I can't actually remove myself, so I'll let someone else do that if they feel so inclined.

We can continue to give UCOSP students access to create their own branches etc. on the main repository, but we should stop folks from putting things into master _unless_ the CI checks pass AND code reviews pass. 

I hope this gives some context, I do wish it was a more obvious problem with Travis, but there is solace in knowing it's not us.

**Comment by TimLethbridge** [comment]
OK. So ahmed needs to fix the PR (which really is just resolving the conflict in en.error)

Then ahmed needs to figure out why a test is failing (a test relating to tracing code ... It seems extraordinary that it is failing though since when I take the compiled code and run it on the test example all is fine).

**Comment by ahmedvc** [comment]
I think I have an idea about this error, and why it behaves differently on my machine. 
- (new [.TemplateTest.]UmpleExceptionHandle ---> the error here.

this issue happens when generating two umple models having different main functions, because we have a static variable JavaClassGenerator.mainMainClass, which is not nullified after the compiler finish generation. 

A quick resolve to it to nullify JavaClassGenerator.mainMainClass = null; before running the next test. I delivered the changes into my repository.

**Comment by TimLethbridge** [comment]
Thanks Ahmed ... glad you have figured out the test thing. Hopefully you will now be able to resolve the conflicts and update this PR

**Comment by TimLethbridge** [comment]
I guess since we know that Travis builds on Linux are failing for many projects, I would be OK, when this PR passes in Travis on Mac, to push it if someone with a linux machine can also test it.

**Comment by Nava2** [comment]
If no one else does, I can in a few hours.

Kevin

**Comment by ahmedvc** [comment]
Hi Kevin, 

Could you please explain briefly the required, or at least the exact git commands that I have to use?

I tried out the given command, and I have the following my branch is 'detached HEAD' state and then "the console rebase - not something we can merge".

**Comment by Nava2** [comment]
Open your console:

``` bash
git checkout master
git pull origin master # Get the most recent master changes
git checkout my-branch # Checkout to the branch required
git rebase master
```

Now, you'll have to manually fix merge conflicts as they arise. To check what files are conflicting, type `git status`

When you fix a file, do: `git add path/to/file`

Once you've fixed all of the conflicts, do: `git rebase --continue`. It'll tell you if you've missed any files. 

When this is all done, you'll need to do: `git push REMOTE my-branch -f`.

Does that make sense?

**Comment by Nava2** [comment]
Oh.. I just realized, you're working with the master branch in your fork. You'll need to do the following:

``` bash
git checkout master # Checkout to your current master branch
git checkout -b f-umple-tl # Now you have a branch named "f-umple-tl" that points to the original "master"
git checkout master # Move back to the original branch
git reset --hard upstream/master # This will reset the "master" branch to be the same commit as "upstream/master"
git pull upstream master # Now it'll match what's in the umple master
git checkout f-umple-tl # Switch back to your new branch
```

Now you do the rebasing. 

All of this nuttiness would be avoided if you use a branch with a "feature" name like `f-umple-tl` that is **not** matched in the umple repository. Working in `master` is a **very** bad idea. Always work in a branch and merge into `master`.

**Comment by TimLethbridge** [comment]
So what I _think_ you are saying is that the sequence in the second comment above will preserve all their changes and put them in a branch called f-umple-tl, and then they issue the rebase command to resolve the conflict. And all this will update this PR too? I find it maddeningly hard to remember these incantations and I am never sure if in fact they are right, since every time I try something it seems to be wrong! Please confirm what I just said. Ultimately all I want is to have this PR updated so that it can be merged by tomorrow morning.

Your two sets of commands together would be: 

`git checkout master # Checkout to your current master branch
git checkout -b f-umple-tl # Now you have a branch named "f-umple-tl" that points to the original "master"
git checkout master # Move back to the original branch
git reset --hard upstream/master # This will reset the "master" branch to be the same commit as "upstream/master"
git pull upstream master # Now it'll match what's in the umple master
git checkout f-umple-tl # Switch back to your new branch
git rebase master
`

Is this correct? I am suspicious that it is not and there is something more needed to update and merge this PR

And by the way the OSX build on Travis master is now failing for a different reason

**Comment by TimLethbridge** [comment]
Crap, The 'code quoting didn't work above for some reason.

```
git checkout master # Checkout to your current master branch
```

   git checkout -b f-umple-tl # Now you have a branch named "f-umple-tl" that points to the original "master"
    git checkout master # Move back to the original branch
    git reset --hard upstream/master # This will reset the "master" branch to be the same commit as "upstream/master"
    git pull upstream master # Now it'll match what's in the umple master
    git checkout f-umple-tl # Switch back to your new branch
    git rebase master

**Comment by ahmedvc** [comment]
I'm doing your steps literally, so I had the following error for the following step:
git reset --hard upstream/master

The error is 
"upstream/master" unknown revision or path 

I think it should be "origin/master", but I need to double check. 

I finished the above mentioned steps with "origin/master" and noticed conflict changes in 699 files.

**Comment by Nava2** [comment]
@TimLethbridge 

> So what I think you are saying is that the sequence in the second comment above will preserve all their changes and put them in a branch called f-umple-tl, and then they issue the rebase command to resolve the conflict. And all this will update this PR too? I find it maddeningly hard to remember these incantations and I am never sure if in fact they are right, since every time I try something it seems to be wrong! Please confirm what I just said. Ultimately all I want is to have this PR updated so that it can be merged by tomorrow morning.

You're completely correct! The problem is actually due to the fact that @ahmedvc  was working in a branch with the same name, thus without breaking the reference to this repo's `master` locally, it needs to be renamed. 

The incantations come with practice, in theory, one should **not** have to write as much as I did here. The following should _normally_ be adequate: 

``` bash
git checkout -b f-my-new-feature # Create a new branch to work with
# ... do some changes
git add -A . # Add my changes to be staged
git commit # Commit my changes
git push origin f-my-new-feature # Push my changes to the feature branch in the 'origin' remote
```

The big difference in workflow between SVN and Git is that you have to stage your changes locally before you commit, then push your changes to the repository. Whereas in SVN it was just, change then commit+push in one action.

To put in code with multiple lines, use three back-ticks (```), then start on a new line below it. End with three more ticks on their own line. :+1:

@ahmedvc, what does the output of `git remote -v` look like for you?
Here is mine: 

```
$ git remote -v
aforward        git@github.com:aforward/umple.git (fetch)
aforward        git@github.com:aforward/umple.git (push)
origin  git@github.com:Nava2/umple.git (fetch)
origin  git@github.com:Nava2/umple.git (push)
upstream        git@github.com:umple/umple.git (fetch)
upstream        git@github.com:umple/umple.git (push)
```

My `upstream` is the main repository. You should point one remote to the `upstream` repository and then have `origin` point to your fork. This way, when you do `git pull upstream master` it fetches from the main repository's `master` branch!

**Comment by ahmedvc** [comment]
I see

**Comment by Nava2** [comment]
Okay, so based on what you wrote: 

> ```
> origin https://github.com/ahmedvc/umple.git (fetch)
> origin https://github.com/ahmedvc/umple.git (push)
> umple https://github.com/umple/umple.git (fetch)
> umple https://github.com/umple/umple.git (push)
> ```

When I wrote `upstream` you want to use `umple`!

**Comment by ahmedvc** [comment]
Yes, I changed them.

**Pull request closed without merging**
