### PR TITLE
Refactoring GvEntityRelationshipDiagram generator

### PR DESCRIPTION
**Pull request by gublan24**
This PR refactors GvEntityRelationshipDiagram generator into a feature "EntityRelationshipGenerator". Since this generator does not have test cases, I did two full compilation of Umple; one with enabling the feature (EntityRelationshipGenerator) and another without using the feature/mixset. The two compilations give the same result.

### CODE REVIEW

**Comment by TimLethbridge** [comment]
There is indeed a test for this:

cruise.umple/test/cruise/umple/implementation/gv/GvErdGeneratorTest.java

**Comment by gublan24** [comment]
I see there are 16 failures that always there. However, when I delete the line "use EntityRelationshipGenerator;", which should ideally cause tests in GvErdGeneratorTest.java to fail has no effect. 

Are these test cases excluded from checking when build Umple? I use dev-tools/bumple to do the complete compilation.

**Comment by TimLethbridge** [comment]
I know the student working on class diagrams caused the ER testcases to fail, since there is some common code (take a look). So I am sure the test cases are being run. I don't have time to investigate.

**Comment by gublan24** [comment]
The test cases not failing also the generator is not there because of the code `System.exit(-1);` in the UmpleModel. This code kills the thread of compilation. And because there is no errors, Junit gives false positive results. See the effect when removing it in https://github.com/umple/umple/tree/disabledCodeGvEntityRelationshipDiagramAsFeature.

**Pull request merged**
