### PR TITLE
JsDiagramDrawingLibrary

### PR DESCRIPTION
**Pull request by marc22alain**
To pull in new features: elaborating association details; association and class types; showing/hiding attributes and methods.

### CODE REVIEW

**Comment by TimLethbridge** [comment]
Looks good. I will merge and make it accessible on umpleonline/test

**Comment by vahdat-ab** [comment]
@TimLethbridge I wonder if we need to merge the pull request? I see that you just closed the pull request.

**Comment by Nava2** [comment]
I know it's not entirely relevant, but well done, @marc22alain! This looks like massive steps forward from your first request. 👍

**Comment by TimLethbridge** [comment]
I meant to merge! Done now.

**Pull request merged**
