### PR TITLE
Fix 1134

### PR DESCRIPTION
**Pull request by JoshuaMcManus**
## Description

Do statements for state machines did not output // line ## "Filename" comments. This fixes this by injecting the comment into the generated Java code.

## Tests

Changes two tests to verify comments.

Fixes Issue #1134

### CODE REVIEW

**Comment by vahdat-ab** [comment]
@AlexJoshuaMcManus please check why your build is failing

**Comment by JoshuaMcManus** [comment]
@vahdat-ab it looks like the tests all passed in Eclipse, but when they're run in test suite they fail because the relative directory changes for the // line output.

How would you suggest I test my changes, if at all?

**Comment by vahdat-ab** [comment]
@AlexJoshuaMcManus 
I tried on my own machine, I faced some failures.
```
    [junit] TEST cruise.umple.statemachine.implementation.StateMachineTest FAILED
    [junit] TEST cruise.umple.statemachine.implementation.java.JavaStateMachineTemplateTest FAILED
    [junit] Tests FAILED
```
When I switch to `master`, it passes all test cases. It means there are issues in your branch.

**Comment by JoshuaMcManus** [comment]
@vahdat-ab 

Sorry, I guess I wasn't clear. Yes I know the tests that I implemented are the ones that are failing. This is because I modified existing tests to look for the new comment that reads:
// line ## "path/to/file"

However, when the tests are run in Eclipse, the path to file is something like "../file.ump", but when the tests are run during a full build they look more like: "../../.../../cruise.umple/test/file.ump"

How would you suggest I go about fixing this? The tests are looking for the comments to match (since that is what I implemented), but it looks like the relative directory changes depending on how the test is called.

**Comment by vahdat-ab** [comment]
I see.
The main priority is the command line. The server always runs tests cases through the command line.
w.r.t to the issue with `Eclipse`, I would say check other test cases in which we test the location and address of files. We have not had any issue with it.

**Comment by JoshuaMcManus** [comment]
@vahdat-ab I've changed the test so it's now passing the build,  but I noticed that 3/4 Travis builds are failing, is that supposed to happen? I remember always failing 2, but not 3.

**Pull request merged**
