### PR TITLE
Fixes #1132 Enables add and delete transitions on state diagram 

### LINKED ISSUE #1132: Allow state machine modification in JointJs diagram
## Brief Description

Currently the implementation UmpleSync does not have action that update umpleCode that correspond to when the stateMachine diagram is changes. This is because the only option (graphViz) UmpleOnline used to have for showing state machine diagram does not allow modification. However JointJs diagram showing state machine allows same operation as class diagram (moving transition end, delete transition). New UmpleSync action should be added to update code once user modify the diagram (DeleteTransitionAction, AddTransitionAction). Edit Transition action will be implementation as a combination of removing then adding as discussed in issue #1127 (same data structure)

***Note:*** This is related to issue #600 

## Tesing

JUnit testing should be added to test the new feature works as expected

### PR DESCRIPTION
**Pull request by glorialaw**
Fixes 1132, allows adding and deleting transitions on the UML state diagram. Changes are reflected in the umple code. By default, the new transition starts with event1.

### CODE REVIEW

**Comment by TimLethbridge** [comment]
@glorialaw   So test DeleteTransitionActionTest is failing.

**Comment by glorialaw** [comment]
I have fixed the test and made sure it worked with full build

**Comment by TimLethbridge** [comment]
@glorialaw There are still some failures in cruise.umple.sync.DeleteTransitionActionTest

**Comment by TimLethbridge** [comment]
@glorialaw it seems to me you are not looking at the QA page generated when you do a full build, as you would see the failed tests before pushing. The page is found in dist/qa/

**Comment by glorialaw** [comment]
@TimLethbridge Thank you for letting me know about the QA page. When I manually test using the test cases using umpleonline they work but I am not sure why it is not working when the the test case. Is there a way to debug this?

**Comment by TimLethbridge** [comment]
@glorialaw Are you certain the test cases are all working on your platform. Just because it says the build successfully, it doesn't mean anything. You always have to check the QA page generated by your full build, and look for any listed errors or failures. The QA page tells you exactly how a given test failed. If you see nothing, then that is strange. I may need to run a build of your branch and check it out myself, or enable Appveyor to give you more details.

**Comment by glorialaw** [comment]
The tests also say that they failed on my end. However, when I put them into umpleonline individually and execute them, it produces the correct output so I’m not sure why it fails.

On Nov 23, 2018, at 11:14 AM, TCLethbridge <notifications@github.com<mailto:notifications@github.com>> wrote:


@glorialaw<https://github.com/glorialaw> Are you certain the test cases are all working on your platform. Just because it says the build successfully, it doesn't mean anything. You always have to check the QA page generated by your full build, and look for any listed errors or failures. The QA page tells you exactly how a given test failed. If you see nothing, then that is strange. I may need to run a build of your branch and check it out myself, or enable Appveyor to give you more details.

**Comment by TimLethbridge** [comment]
@glorialaw So I can easily reproduce the issues on my computer. I just do a quick build, and then run only the template tests using the following command.
```
ant -f build.umple.xml template.test
```

Then you look at the qa page. Here is the first failure

```
DeleteTransitionActionTest | Go_WrongDirectionTransition | Failure | Failed at:8 expected:< }[]> but was:< }[ ]>
```
This is simply saying that there is an extra space at this point.

The second failure is

```
DeleteTransitionActionTest | Go_LastTransition | Failure | Failed at:4 expected:< select[Drive -> driv]e;> but was:< select[Reverse -> revers]e;>
```
The wrong transition appears.

The third failure is similar
```
NewTransitionTest | Go_SameFromId | Failure | Failed at:4 expected:< []selectDrive -> drive...> but was:< [ ]selectDrive -> drive...>
```

**Comment by glorialaw** [comment]
I have fixed all the issues and verified with the QA now. Thanks for your help Tim!

**Comment by TimLethbridge** [comment]
Before I can merge this, we need a change so that 
'Transition' only appears on the palette when in js mode, and otherwise is hidden. By the same token the other items should also be hidden in that mode. I may try to do this myself as really it should be consistent across all the modes.

**Comment by TimLethbridge** [comment]
This pull request is old and operates on state diagrams in Joint.js, but the code is OK, so I am merging it so it is not left behind. The feature is not activated, since considerable work on Joint,js is still needed

**Pull request merged**
