### PR TITLE
implemented code injections for user-defined methods

### PR DESCRIPTION
**Pull request by Shikib**
This pull request contains the implementation of functionality that would allow users to perform before/after injections on custom defined methods.

For example if you have:

```
class A {
  void foo(int x) {
    if(x < 0) {
      return;
    }
    System.out.println("foo");
  }

  after foo {
     System.out.println("bar");
  }  
```

This is something that previously did not perform the injection but will after this pull request. Right now what I'm doing is:

For before code injections:
- Placing the injection at the start of the method

For after code injections:
- Placing the injection before every return statement
- Placing the injection at the end of the method body if there are no return statement
- Placing the injection at the end of the method body if there are return statements but the last line isn't a return (consider example above for this).

The majority of the code in this PR is to deal with the indentation of the injected code, the actual implementation part is fairly simple.

### CODE REVIEW

**Comment by TimLethbridge** [comment]
Does it work properly when a return statement is on the same line as other stuff or is in a conditional without braces. This may be bad style, but it should work?
   if (a=5) return(b);

**Comment by TimLethbridge** [comment]
Oh no!

You have edited generated code.

The JavaClassGenerator.java
is coming from Jet

**Comment by Shikib** [comment]
I moved the implementation to the .jet file. 

I don't think my current implementation handles this code:

```
if (a==5) return b;
```

The problem isn't that the return is on the same line though, it can handle the following reasonable well (i.e., the formatting is a bit off, but it's valid code nonetheless).

```
if (a==5) { return b; }
```

The problem is that my implementation expects that if a return is in a code block, we can simply insert the lines of code directly above the return statement and all of the code will remain in that block. This however isn't necessarily true.

```
if (a == 5)
  return b;
```

If code (eg. a System.out.println(b)) was to be injected into there, my current implementation would generate:

```
if (a==5) 
  System.out.println(b);
  return b;
```

Which is incorrect because the return is outside of the if statement (at least in Java/cpp -- I think ruby/php don't have this issue). 

What would be an acceptable way of handling this? I can't think of any approach that would allow me to detect whether a code block has braces surrounding it (because if we knew it didn't have braces, we'd inject the braces for the code block along with our code injection), without relying on external factors like indentation (which doesn't seem like a great approach as Umple doesn't enforce any indentation rules).

**Comment by TimLethbridge** [comment]
See my comments on the original issue regarding another option.

**Comment by Shikib** [comment]
@TimLethbridge: I fixed the issues that were identified earlier.

At this point in time, the following *.ump file:

```
class A {

  void setK() {
    if(test) {
      return b;
    }

    if(test)
      return b;

    if(test) {
      // )
      return b;
    }

    if(test)
      // {
      return b;

    if(test)
      /*
           {
      */
      return b;

    if(test) {
      /*
           )
      */
      return b;
    }

    if(test)return b;

    if(test)     return b;

    if(test) { return b; }

    if(test) {    return b; }

  }

  before setK {
    // foo
  }

  after setK {
    // bar
  }
}
```

will generate the following .java file:

```
/*PLEASE DO NOT EDIT THIS CODE*/
/*This code was generated using the UMPLE @UMPLE_VERSION@ modeling language!*/



// line 1 "helloworld.ump"
public class A
{

  //------------------------
  // MEMBER VARIABLES
  //------------------------

  //------------------------
  // CONSTRUCTOR
  //------------------------

  public A()
  {}

  //------------------------
  // INTERFACE
  //------------------------

  public void delete()
  {}

  // line 4 "helloworld.ump"
  public void setK(){
    // line 43 "helloworld.ump"
    // foo
    if(test) {
      // line 47 "helloworld.ump"      
      // bar
      return b;
    }

    if(test) {
    // line 47 "helloworld.ump"      
      // bar
      return b;
    }

    if(test) {
      // )
      // line 47 "helloworld.ump"      
      // bar
      return b;
    }

    if(test) {
      // {
     // line 47 "helloworld.ump"      
      // bar
      return b;
    }

    if(test) {
      /*
           {
      */
     // line 47 "helloworld.ump"      
      // bar
      return b;
    }

    if(test) {
      /*
           )
      */
      // line 47 "helloworld.ump"      
      // bar
      return b;
    }

    if(test) {
    // line 47 "helloworld.ump"      
      // bar
      return b;
    }

    if(test) {
    // line 47 "helloworld.ump"      
      // bar
      return b;
    }

    if(test) {
      // line 47 "helloworld.ump"      
      // bar
      return b;
    }

    if(test) {
      // line 47 "helloworld.ump"      
      // bar
      return b;
    }
    // line 47 "helloworld.ump"
    // bar
  }

}
```

Proper functionality of code + indentation is preserved.

**Comment by Shikib** [comment]
I fixed all of the previously identified issues with the code injection into user defined methods. The following .ump file, which encompasses all the various cases that I predicted would cause issues, generates the .java file that I would expect it to:

Umple file:

```
class A {

  void setK() {
    if(test) {
      return b;
    }

    if(test)
      return b;

    if(test) {
      // )
      return b;
    }

    if(test)
      // {
      return b;

    if(test)
      /*
           {
      */
      return b;

    if(test) {
      /*
           )
      */
      return b;
    }

    if(test)return b;

    if(test)     return b;

    if(test) { return b; }

    if(test) {    return b; }

  }

  before setK {
    // foo
  }

  after setK {
    // bar
  }
}

```

Generated Java file:

```
/*PLEASE DO NOT EDIT THIS CODE*/
/*This code was generated using the UMPLE @UMPLE_VERSION@ modeling language!*/



// line 1 "helloworld.ump"
public class A
{

  //------------------------
  // MEMBER VARIABLES
  //------------------------

  //------------------------
  // CONSTRUCTOR
  //------------------------

  public A()
  {}

  //------------------------
  // INTERFACE
  //------------------------

  public void delete()
  {}

  // line 4 "helloworld.ump"
  public void setK(){
    // line 43 "helloworld.ump"
    // foo
    if(test) {
      // line 47 "helloworld.ump"
      // bar
      return b;
    }

    if(test) {
      // line 47 "helloworld.ump"
      // bar
      return b;
    }

    if(test) {
      // )      
      // line 47 "helloworld.ump"
      // bar
      return b;
    }

    if(test) {
      // {      
      // line 47 "helloworld.ump"
      // bar
      return b;
    }
    if(test) {
      /*
           {
      */
      // line 47 "helloworld.ump"
      // bar
      return b;
    }

    if(test) {
      /*
           )
      */
      // line 47 "helloworld.ump"
      // bar
      return b;
    }

    if(test) {
      // line 47 "helloworld.ump"
      // bar
      return b;
    }

    if(test) {
      // line 47 "helloworld.ump"
      // bar
      return b;
    }

    if(test) {
      // line 47 "helloworld.ump"
      // bar
      return b;
    }

    if(test) {
      // line 47 "helloworld.ump"
      // bar
      return b;
    }
    // line 47 "helloworld.ump"
    // bar
  }

}
```

**Comment by TimLethbridge** [comment]
Looks promising! But can you please add an actual automated test.

Not clear why appveyor build gives different results from Travis! Some strange generated java seems to be hanging around in Appveyor.

**Comment by TimLethbridge** [comment]
I see the builds are passing! But I don't see any automated tests yet. These are needed

**Comment by TimLethbridge** [comment]
Any progress on getting some tests into place for this @Shikib

**Comment by Shikib** [comment]
I do have some tests written locally. The reason I haven't pushed them yet is because the code injection functionality isn't currently active. The reason for this, which I briefly mentioned in our last meeting, is that until now -- a number of Umple developers have used code injections with the assumption that the code injections wouldn't inject into custom defined methods.

For example, something that I've seen a few times throughout the codebase is the following scenario. Say the method `setFoo(aFoo)` is automatically generated. The developer would then go and define the following method:

```
void setFoo(String aFooName, int aFooInt) {
  ...
}

after setFoo {
  System.out.println(aFoo.toString());
}
```

Because I don't think that the code injection changes should break any existing code (i.e., I don't think it's a good idea to go an rename every instance of such a method in the codebase), I decided to go with requiring a different syntax for code injections into custom methods. 

So for example, if someone wanted to inject code into all methods named setFoo (including custom defined ones), they'd do something like:

```
after setFoo~ {
  a = test;
}
```

I think we should discuss what the syntax is (I don't necessarily think a tilde is the best option), but right now I'm just working on changing how the code injection tokens and code injections objects are created to allow this to work. This ties in heavily to the next thing I'm working on, code injections with parameters specified, so a lot of the work I'm doing for this will be transferable to that.

So no functionality will exist, until I add in the new syntax parsing for custom code injections. When I do that, I will modify the tests (to use the new syntax) and then update the pull request.

**Comment by vahdat-ab** [comment]
chek the issue #710 for more comments.

**Comment by TimLethbridge** [comment]
This looks excellent. Good work. @vahdat-ab do you have any comments? If you want I can merge this after Morgan's work goes through.

**Comment by vahdat-ab** [comment]
@TimLethbridge  I'm checking the code. Inform you soon.

**Comment by vahdat-ab** [comment]
It looks it is working, I need more explanaition though. However, it's safe to go head.

**Pull request merged**
