### PR TITLE
Issue607

### PR DESCRIPTION
**Pull request by amidzak**
Fix for issue 607

### CODE REVIEW

**Comment by Nava2** [comment]
On your computer where you're writing `git` commits to, you need to update your config values: 

```
git config --global user.name "John Doe" # This looks to be correct already
git config --global user.email johndoe@example.com # Make sure this is the e-mail associated with your Github Account
```

You should then run `git rebase -i master` on your branch to rebase the commits into a single commit and fix the author at the same time. [This tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase/) explains `rebase` pretty well. 

The reason we have the authors fixed is that when looking at pages like [this](https://github.com/amidzak/umple/commit/255426000310f4eee3b3fa8866236405bab2b22f) the author of the commit is _not_ linked to your github page. This means we lose functionality.

**Comment by vahdat-ab** [comment]
Thanks Amid.

**Comment by TimLethbridge** [comment]
I didn't see Nava2's comments ... I was working on verifying the changes and when all was OK with them I merged.

**Comment by Nava2** [comment]
Not a big deal, just fix the authors for next time. No point fretting about it now!

**Pull request merged**
