### PR TITLE
Resolve issue 1008

### PR DESCRIPTION
**Pull request by jblang94**
# Description
This PR addresses issue #1008. Umple now supports enumerations. A user can define enumerations inside or outside of classes. Enumerations defined outside of classes are shared between classes. The `enumerationDefinition` rule is in umple_classes.grammar. A new `UmpleEnumeration` type has been created as well.

An "Enumerations" section is now in the Umple User Manual.

# New Tests
### UmpleParserTest
- parseUmpleEnumerationDefinedInClass
- parseUmpleEnumerationDefinedAtTopLevel
- parseUmpleEnumerationDefinedAtTopLevelAndInClass

### JavaClassTemplateTest
- TestUmpleEnumerations_*

### CODE REVIEW

**Comment by vahdat-ab** [comment]
Cool. Thanks.
Please consider the following example:
```
enum Month {january, february, March}
enum Fruit {apple, orange}
class X1{
  Month month;
}
class X2{
   Fruit t;
}
```
When the code is generated, I see that both enumeration types are defined in both classes. However, this should not happen because class `X1` just needs the enumeration Month and class `X2` just needs the enumeration Fruit.
Another example is this
```

enum Month {january, february, March}
enum Fruit {apple, orange}
class X{}
class X2{}
```
The generator still puts the enumeration in these classes.

> The solution

Simply check if the enumeration has been used for attribute types, parameters of methods, or parameters of events of state machines. If it's been used once, then put the definition of enumeration inside the class.

For sure, this is going to be valid just for model-level enumerations

**Comment by jblang94** [comment]
@vahdat-ab Thanks for the feedback! Updated my solution

**Comment by vahdat-ab** [comment]
Good, thanks.
You also need to make sure the names are unique. Please consider the following example:
```
enum Month {x,y,z}
enum Month {o,p,q}
class A{
  Month m;
  Month p;
}
```
The Umple compiler easily passes this. It must be detected and a proper error must be raised.
Another example
```
enum Month {x,y,z}
class A{
  enum Month {o,p,q}
  Month m;
  Month p;
}
```

In this case, there is no error because the local version has a priority over the model-level enumeration. You need to make sure you don't generate the definition for `enum Month {x,y,z}` in class A.
Make sure you also document the error.

**Comment by jblang94** [comment]
@vahdat-ab I also added detection for duplicate enumerations within an Umple class

**Comment by vahdat-ab** [comment]
Great.
Just a note: when you resolve any kind of problem, you need to consider all possible cases:
Check this example:
```
enum X{x}
enum Y{y}
class X{
  X t;
}
```
Now, which type does attribute `t` have? Indeed, the name of model-level enumerations must be unique in the model. The internal enumerations do not need to have this restriction. They cannot have the same name as their classes have.
This example is valid:
```
class X{
  enum Y{y}
  Y t; // Y is not a class here
}
class Y{
}
```
This example is invalid:
```
class X{
  enum X{x}
  X t;
}

```

One more case that can cause conflict. Consider the following example: 
```
class X{
  enum Y{y}
  0..1 -- *Y;
}
class Y{
}
```
Now, `x` has an association with class `Y` or enumeration `Y`!!!. It is enumeration `Y1`, but we cannot have a bidirectional association between a class and enumeration. Indeed, when you generate the code, you will not see a compilation error because the definition of enumeration has priority or the definition of class `Y`. Class `X` will have many enumerations of `Y` and class `Y` will have `0..1` of class `X`. This is wrong because we wanted to make an association between class `X` and class `Y`. You need to detect this case and raise a proper error.
However, this example is valid:
```
class X{
  enum Y{y}
  0..1 -> * Y;
}
class Y{
}
```
In this case, because the association is directional, there is no issue. The class will make an association between class `X` and enumeration `Y`. In this case, don't make an error and just warn the user about the ambiguity and the real output (which is no association between class `X` and class `Y`, but one between class `X` and enumeration `Y`). Make sure the generated code is correct for this cases.
NOTE: enumerations and interfaces somehow have the same restriction while they are used in associations.

**Comment by jblang94** [comment]
Closed this PR because the solution still needs to be refined. All feedback received has been moved to #1008

**Pull request closed without merging**
